@echo off
echo 🔄 [DOCS-AUTO-UPDATE-HOOK] Aggiornamento automatico documentazione...

REM ===== VERIFICA MODIFICHE DATABASE =====
echo 📊 Verifica modifiche database...

REM Check if there were recent database changes that require doc update
set "update_needed=0"

REM Check git status for schema-related changes
git status --porcelain | findstr /i "supabase\|schema\|migration" >nul
if %errorlevel% eq 0 (
    set "update_needed=1"
    echo ✅ Rilevate modifiche database - aggiornamento documentazione necessario
) else (
    echo ℹ️  Nessuna modifica database rilevata
)

REM Check if DOCUMENTAZIONE_VERSIONE_ATTUALE.md is older than 1 day (optional check)
if exist "docs\project\DOCUMENTAZIONE_VERSIONE_ATTUALE.md" (
    for /f %%i in ('powershell -Command "(Get-Date) - (Get-Item 'docs\project\DOCUMENTAZIONE_VERSIONE_ATTUALE.md').LastWriteTime | Select-Object -ExpandProperty Days"') do set "days_old=%%i"
    if !days_old! gtr 1 (
        echo ⚠️  Documentazione database più vecchia di 1 giorno - aggiornamento consigliato
        set "update_needed=1"
    )
)

REM ===== ESEGUI AGGIORNAMENTO SE NECESSARIO =====
if "%update_needed%"=="1" (
    echo 🔄 Esecuzione dump schema e aggiornamento documentazione...
    
    pushd "supabase-fixes\schema-reference"
    
    REM Eseguire dump schema completo (che include anche la generazione ER)
    call dump-schema.bat
    
    popd
    
    echo ✅ Documentazione database aggiornata automaticamente
    
    REM ===== AUTO-COMMIT DOCUMENTATION CHANGES =====
    echo 📝 Verifica modifiche documentazione per auto-commit...
    
    git status --porcelain | findstr "DOCUMENTAZIONE_VERSIONE_ATTUALE.md" >nul
    if %errorlevel% eq 0 (
        echo 💾 Auto-commit delle modifiche documentazione...
        git add "docs\project\DOCUMENTAZIONE_VERSIONE_ATTUALE.md"
        git commit -m "docs: auto-update database documentation with latest schema

- Updated ER diagrams (complete + simplified)
- Refreshed table definitions from live database
- Timestamp: %date% %time%

🤖 Auto-generated by docs-auto-update-hook.bat"
        
        echo ✅ Documentazione committata automaticamente
    ) else (
        echo ℹ️  Nessuna modifica alla documentazione da committare
    )
    
) else (
    echo ℹ️  Documentazione up-to-date, nessun aggiornamento necessario
)

REM ===== VERIFICA COERENZA PROJECT_OVERVIEW =====
echo 🔍 Verifica coerenza con PROJECT_OVERVIEW.md...

if exist "docs\project\PROJECT_OVERVIEW.md" (
    REM Check if PROJECT_OVERVIEW needs update based on recent changes
    git log --since="1 day ago" --oneline --grep="feat\|fix\|database" | findstr /v "^$" >nul
    if %errorlevel% eq 0 (
        echo 💡 SUGGERIMENTO: Considera aggiornamento PROJECT_OVERVIEW.md per recenti modifiche funzionali
        echo    Esegui manualmente: Update project status in PROJECT_OVERVIEW.md
    ) else (
        echo ✅ PROJECT_OVERVIEW.md probabilmente up-to-date
    )
) else (
    echo ⚠️  WARNING: PROJECT_OVERVIEW.md non trovato!
)

REM ===== CLEANUP E REPORT =====
echo.
echo 📊 [DOCS-AUTO-UPDATE-HOOK] Report finale:
echo ===============================================
if "%update_needed%"=="1" (
    echo ✅ Documentazione database aggiornata automaticamente
    echo 📊 Diagrammi ER regenerati con schema attuale
    echo 💾 Modifiche committate automaticamente
) else (
    echo ✅ Documentazione già up-to-date
)
echo 📝 PROJECT_OVERVIEW.md: Verifica manuale consigliata
echo.
echo 🎯 Hook completato con successo!
pause