
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfbaomnccefkpqnfjjiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmYmFvbW5jY2Vma3BxbmZqaml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTg4NzQsImV4cCI6MjA3MTE3NDg3NH0.QqN16sDaaTrru8XeyNGdX4sZtXVgsMh6rUEijf8VO5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Enhanced security configurations
    flowType: 'pkce', // Use PKCE flow for better security
    detectSessionInUrl: true,
    storageKey: 'sb-auth-token',
    // Prevent redirect vulnerabilities
    redirectTo: `${window.location.origin}/auth/callback`,
  },
  global: {
    headers: {
      'x-application-name': 'diagram-app'
    }
  },
  realtime: {
    timeout: 30000
  }
});
